#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
Created on 2018年5月23日

@author: ADMINISTRATION
"""
${importClasses}

class ${SimpleName}(${superClass}):
    def __init__(self):
        ${superClass}.__init__(self)
        ${selfField}
    ${modelMethods}

    ${list_dict_2_object}